### ISSUE TITLE
Bug in `tool_executor.run_conversation`

### ISSUE THREAD

**Issue by danieljannai21** [microsoft/ToolTalk#6]
I think there's a bug in `tool_executor.run_conversation`. You should be adding the api messages to `ground_truth_history` before adding the assistant message that is their result.

That is, this block of code:
https://github.com/microsoft/ToolTalk/blob/a8d8befb1ea098cd9fc363a7515028b0b2aeb903/src/tooltalk/evaluation/tool_executor.py#L305
should appear before this one:
https://github.com/microsoft/ToolTalk/blob/a8d8befb1ea098cd9fc363a7515028b0b2aeb903/src/tooltalk/evaluation/tool_executor.py#L301

**Comment by minjie-cohere** [comment]
yes i believe that's correct. we (@cohere-ai) have been working on top of this repo recently and found several "bugs" too. hope to make contributions back and share what we've found with the community soon!
